server:
  port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helper
    username: root
    password: Cr@123456
#项目自定义配置
project:
  use-mock-component: true

#持久层框架配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  file:
    name: D:\tmp\TestHelp.log