package com.cream.helper.core.net.proto.clazz;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file/Common.proto

public final class CommonProto {
    private CommonProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface LoginReqOrBuilder extends
            // @@protoc_insertion_point(interface_extends:LoginReq)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string username = 1;</code>
         *
         * @return The username.
         */
        java.lang.String getUsername();

        /**
         * <code>string username = 1;</code>
         *
         * @return The bytes for username.
         */
        com.google.protobuf.ByteString
        getUsernameBytes();

        /**
         * <code>string password = 2;</code>
         *
         * @return The password.
         */
        java.lang.String getPassword();

        /**
         * <code>string password = 2;</code>
         *
         * @return The bytes for password.
         */
        com.google.protobuf.ByteString
        getPasswordBytes();
    }

    /**
     * Protobuf type {@code LoginReq}
     */
    public static final class LoginReq extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:LoginReq)
            LoginReqOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use LoginReq.newBuilder() to construct.
        private LoginReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LoginReq() {
            username_ = "";
            password_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginReq();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private LoginReq(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            username_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            password_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CommonProto.internal_static_LoginReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CommonProto.internal_static_LoginReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            CommonProto.LoginReq.class, CommonProto.LoginReq.Builder.class);
        }

        public static final int USERNAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object username_;

        /**
         * <code>string username = 1;</code>
         *
         * @return The username.
         */
        @java.lang.Override
        public java.lang.String getUsername() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                username_ = s;
                return s;
            }
        }

        /**
         * <code>string username = 1;</code>
         *
         * @return The bytes for username.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getUsernameBytes() {
            java.lang.Object ref = username_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                username_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PASSWORD_FIELD_NUMBER = 2;
        private volatile java.lang.Object password_;

        /**
         * <code>string password = 2;</code>
         *
         * @return The password.
         */
        @java.lang.Override
        public java.lang.String getPassword() {
            java.lang.Object ref = password_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                password_ = s;
                return s;
            }
        }

        /**
         * <code>string password = 2;</code>
         *
         * @return The bytes for password.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            java.lang.Object ref = password_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof CommonProto.LoginReq)) {
                return super.equals(obj);
            }
            CommonProto.LoginReq other = (CommonProto.LoginReq) obj;

            if (!getUsername()
                    .equals(other.getUsername())) return false;
            if (!getPassword()
                    .equals(other.getPassword())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + USERNAME_FIELD_NUMBER;
            hash = (53 * hash) + getUsername().hashCode();
            hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
            hash = (53 * hash) + getPassword().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static CommonProto.LoginReq parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginReq parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginReq parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginReq parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginReq parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginReq parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginReq parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.LoginReq parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.LoginReq parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static CommonProto.LoginReq parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.LoginReq parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.LoginReq parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(CommonProto.LoginReq prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code LoginReq}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:LoginReq)
                CommonProto.LoginReqOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return CommonProto.internal_static_LoginReq_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return CommonProto.internal_static_LoginReq_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                CommonProto.LoginReq.class, CommonProto.LoginReq.Builder.class);
            }

            // Construct using CommonProto.LoginReq.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                username_ = "";

                password_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return CommonProto.internal_static_LoginReq_descriptor;
            }

            @java.lang.Override
            public CommonProto.LoginReq getDefaultInstanceForType() {
                return CommonProto.LoginReq.getDefaultInstance();
            }

            @java.lang.Override
            public CommonProto.LoginReq build() {
                CommonProto.LoginReq result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public CommonProto.LoginReq buildPartial() {
                CommonProto.LoginReq result = new CommonProto.LoginReq(this);
                result.username_ = username_;
                result.password_ = password_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof CommonProto.LoginReq) {
                    return mergeFrom((CommonProto.LoginReq) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(CommonProto.LoginReq other) {
                if (other == CommonProto.LoginReq.getDefaultInstance()) return this;
                if (!other.getUsername().isEmpty()) {
                    username_ = other.username_;
                    onChanged();
                }
                if (!other.getPassword().isEmpty()) {
                    password_ = other.password_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                CommonProto.LoginReq parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (CommonProto.LoginReq) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object username_ = "";

            /**
             * <code>string username = 1;</code>
             *
             * @return The username.
             */
            public java.lang.String getUsername() {
                java.lang.Object ref = username_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    username_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string username = 1;</code>
             *
             * @return The bytes for username.
             */
            public com.google.protobuf.ByteString
            getUsernameBytes() {
                java.lang.Object ref = username_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    username_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string username = 1;</code>
             *
             * @param value The username to set.
             * @return This builder for chaining.
             */
            public Builder setUsername(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                username_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string username = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUsername() {

                username_ = getDefaultInstance().getUsername();
                onChanged();
                return this;
            }

            /**
             * <code>string username = 1;</code>
             *
             * @param value The bytes for username to set.
             * @return This builder for chaining.
             */
            public Builder setUsernameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                username_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object password_ = "";

            /**
             * <code>string password = 2;</code>
             *
             * @return The password.
             */
            public java.lang.String getPassword() {
                java.lang.Object ref = password_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    password_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string password = 2;</code>
             *
             * @return The bytes for password.
             */
            public com.google.protobuf.ByteString
            getPasswordBytes() {
                java.lang.Object ref = password_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    password_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string password = 2;</code>
             *
             * @param value The password to set.
             * @return This builder for chaining.
             */
            public Builder setPassword(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                password_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string password = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearPassword() {

                password_ = getDefaultInstance().getPassword();
                onChanged();
                return this;
            }

            /**
             * <code>string password = 2;</code>
             *
             * @param value The bytes for password to set.
             * @return This builder for chaining.
             */
            public Builder setPasswordBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                password_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:LoginReq)
        }

        // @@protoc_insertion_point(class_scope:LoginReq)
        private static final CommonProto.LoginReq DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new CommonProto.LoginReq();
        }

        public static CommonProto.LoginReq getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LoginReq>
                PARSER = new com.google.protobuf.AbstractParser<LoginReq>() {
            @java.lang.Override
            public LoginReq parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LoginReq(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<LoginReq> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LoginReq> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public CommonProto.LoginReq getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface LoginResOrBuilder extends
            // @@protoc_insertion_point(interface_extends:LoginRes)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 uid = 1;</code>
         *
         * @return The uid.
         */
        long getUid();

        /**
         * <code>repeated .Role role = 2;</code>
         */
        java.util.List<CommonProto.Role>
        getRoleList();

        /**
         * <code>repeated .Role role = 2;</code>
         */
        CommonProto.Role getRole(int index);

        /**
         * <code>repeated .Role role = 2;</code>
         */
        int getRoleCount();

        /**
         * <code>repeated .Role role = 2;</code>
         */
        java.util.List<? extends CommonProto.RoleOrBuilder>
        getRoleOrBuilderList();

        /**
         * <code>repeated .Role role = 2;</code>
         */
        CommonProto.RoleOrBuilder getRoleOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code LoginRes}
     */
    public static final class LoginRes extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:LoginRes)
            LoginResOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use LoginRes.newBuilder() to construct.
        private LoginRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LoginRes() {
            role_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new LoginRes();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private LoginRes(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            uid_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                role_ = new java.util.ArrayList<CommonProto.Role>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            role_.add(
                                    input.readMessage(CommonProto.Role.parser(), extensionRegistry));
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    role_ = java.util.Collections.unmodifiableList(role_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CommonProto.internal_static_LoginRes_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CommonProto.internal_static_LoginRes_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            CommonProto.LoginRes.class, CommonProto.LoginRes.Builder.class);
        }

        public static final int UID_FIELD_NUMBER = 1;
        private long uid_;

        /**
         * <code>int64 uid = 1;</code>
         *
         * @return The uid.
         */
        @java.lang.Override
        public long getUid() {
            return uid_;
        }

        public static final int ROLE_FIELD_NUMBER = 2;
        private java.util.List<CommonProto.Role> role_;

        /**
         * <code>repeated .Role role = 2;</code>
         */
        @java.lang.Override
        public java.util.List<CommonProto.Role> getRoleList() {
            return role_;
        }

        /**
         * <code>repeated .Role role = 2;</code>
         */
        @java.lang.Override
        public java.util.List<? extends CommonProto.RoleOrBuilder>
        getRoleOrBuilderList() {
            return role_;
        }

        /**
         * <code>repeated .Role role = 2;</code>
         */
        @java.lang.Override
        public int getRoleCount() {
            return role_.size();
        }

        /**
         * <code>repeated .Role role = 2;</code>
         */
        @java.lang.Override
        public CommonProto.Role getRole(int index) {
            return role_.get(index);
        }

        /**
         * <code>repeated .Role role = 2;</code>
         */
        @java.lang.Override
        public CommonProto.RoleOrBuilder getRoleOrBuilder(
                int index) {
            return role_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (uid_ != 0L) {
                output.writeInt64(1, uid_);
            }
            for (int i = 0; i < role_.size(); i++) {
                output.writeMessage(2, role_.get(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (uid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, uid_);
            }
            for (int i = 0; i < role_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, role_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof CommonProto.LoginRes)) {
                return super.equals(obj);
            }
            CommonProto.LoginRes other = (CommonProto.LoginRes) obj;

            if (getUid()
                    != other.getUid()) return false;
            if (!getRoleList()
                    .equals(other.getRoleList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + UID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getUid());
            if (getRoleCount() > 0) {
                hash = (37 * hash) + ROLE_FIELD_NUMBER;
                hash = (53 * hash) + getRoleList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static CommonProto.LoginRes parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginRes parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginRes parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginRes parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginRes parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.LoginRes parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.LoginRes parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.LoginRes parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.LoginRes parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static CommonProto.LoginRes parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.LoginRes parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.LoginRes parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(CommonProto.LoginRes prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code LoginRes}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:LoginRes)
                CommonProto.LoginResOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return CommonProto.internal_static_LoginRes_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return CommonProto.internal_static_LoginRes_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                CommonProto.LoginRes.class, CommonProto.LoginRes.Builder.class);
            }

            // Construct using CommonProto.LoginRes.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getRoleFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                uid_ = 0L;

                if (roleBuilder_ == null) {
                    role_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    roleBuilder_.clear();
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return CommonProto.internal_static_LoginRes_descriptor;
            }

            @java.lang.Override
            public CommonProto.LoginRes getDefaultInstanceForType() {
                return CommonProto.LoginRes.getDefaultInstance();
            }

            @java.lang.Override
            public CommonProto.LoginRes build() {
                CommonProto.LoginRes result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public CommonProto.LoginRes buildPartial() {
                CommonProto.LoginRes result = new CommonProto.LoginRes(this);
                int from_bitField0_ = bitField0_;
                result.uid_ = uid_;
                if (roleBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) != 0)) {
                        role_ = java.util.Collections.unmodifiableList(role_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.role_ = role_;
                } else {
                    result.role_ = roleBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof CommonProto.LoginRes) {
                    return mergeFrom((CommonProto.LoginRes) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(CommonProto.LoginRes other) {
                if (other == CommonProto.LoginRes.getDefaultInstance()) return this;
                if (other.getUid() != 0L) {
                    setUid(other.getUid());
                }
                if (roleBuilder_ == null) {
                    if (!other.role_.isEmpty()) {
                        if (role_.isEmpty()) {
                            role_ = other.role_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureRoleIsMutable();
                            role_.addAll(other.role_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.role_.isEmpty()) {
                        if (roleBuilder_.isEmpty()) {
                            roleBuilder_.dispose();
                            roleBuilder_ = null;
                            role_ = other.role_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            roleBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getRoleFieldBuilder() : null;
                        } else {
                            roleBuilder_.addAllMessages(other.role_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                CommonProto.LoginRes parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (CommonProto.LoginRes) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private long uid_;

            /**
             * <code>int64 uid = 1;</code>
             *
             * @return The uid.
             */
            @java.lang.Override
            public long getUid() {
                return uid_;
            }

            /**
             * <code>int64 uid = 1;</code>
             *
             * @param value The uid to set.
             * @return This builder for chaining.
             */
            public Builder setUid(long value) {

                uid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 uid = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearUid() {

                uid_ = 0L;
                onChanged();
                return this;
            }

            private java.util.List<CommonProto.Role> role_ =
                    java.util.Collections.emptyList();

            private void ensureRoleIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    role_ = new java.util.ArrayList<CommonProto.Role>(role_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    CommonProto.Role, CommonProto.Role.Builder, CommonProto.RoleOrBuilder> roleBuilder_;

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public java.util.List<CommonProto.Role> getRoleList() {
                if (roleBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(role_);
                } else {
                    return roleBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public int getRoleCount() {
                if (roleBuilder_ == null) {
                    return role_.size();
                } else {
                    return roleBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public CommonProto.Role getRole(int index) {
                if (roleBuilder_ == null) {
                    return role_.get(index);
                } else {
                    return roleBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder setRole(
                    int index, CommonProto.Role value) {
                if (roleBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRoleIsMutable();
                    role_.set(index, value);
                    onChanged();
                } else {
                    roleBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder setRole(
                    int index, CommonProto.Role.Builder builderForValue) {
                if (roleBuilder_ == null) {
                    ensureRoleIsMutable();
                    role_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    roleBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder addRole(CommonProto.Role value) {
                if (roleBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRoleIsMutable();
                    role_.add(value);
                    onChanged();
                } else {
                    roleBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder addRole(
                    int index, CommonProto.Role value) {
                if (roleBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureRoleIsMutable();
                    role_.add(index, value);
                    onChanged();
                } else {
                    roleBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder addRole(
                    CommonProto.Role.Builder builderForValue) {
                if (roleBuilder_ == null) {
                    ensureRoleIsMutable();
                    role_.add(builderForValue.build());
                    onChanged();
                } else {
                    roleBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder addRole(
                    int index, CommonProto.Role.Builder builderForValue) {
                if (roleBuilder_ == null) {
                    ensureRoleIsMutable();
                    role_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    roleBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder addAllRole(
                    java.lang.Iterable<? extends CommonProto.Role> values) {
                if (roleBuilder_ == null) {
                    ensureRoleIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, role_);
                    onChanged();
                } else {
                    roleBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder clearRole() {
                if (roleBuilder_ == null) {
                    role_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    roleBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public Builder removeRole(int index) {
                if (roleBuilder_ == null) {
                    ensureRoleIsMutable();
                    role_.remove(index);
                    onChanged();
                } else {
                    roleBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public CommonProto.Role.Builder getRoleBuilder(
                    int index) {
                return getRoleFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public CommonProto.RoleOrBuilder getRoleOrBuilder(
                    int index) {
                if (roleBuilder_ == null) {
                    return role_.get(index);
                } else {
                    return roleBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public java.util.List<? extends CommonProto.RoleOrBuilder>
            getRoleOrBuilderList() {
                if (roleBuilder_ != null) {
                    return roleBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(role_);
                }
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public CommonProto.Role.Builder addRoleBuilder() {
                return getRoleFieldBuilder().addBuilder(
                        CommonProto.Role.getDefaultInstance());
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public CommonProto.Role.Builder addRoleBuilder(
                    int index) {
                return getRoleFieldBuilder().addBuilder(
                        index, CommonProto.Role.getDefaultInstance());
            }

            /**
             * <code>repeated .Role role = 2;</code>
             */
            public java.util.List<CommonProto.Role.Builder>
            getRoleBuilderList() {
                return getRoleFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    CommonProto.Role, CommonProto.Role.Builder, CommonProto.RoleOrBuilder>
            getRoleFieldBuilder() {
                if (roleBuilder_ == null) {
                    roleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            CommonProto.Role, CommonProto.Role.Builder, CommonProto.RoleOrBuilder>(
                            role_,
                            ((bitField0_ & 0x00000001) != 0),
                            getParentForChildren(),
                            isClean());
                    role_ = null;
                }
                return roleBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:LoginRes)
        }

        // @@protoc_insertion_point(class_scope:LoginRes)
        private static final CommonProto.LoginRes DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new CommonProto.LoginRes();
        }

        public static CommonProto.LoginRes getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<LoginRes>
                PARSER = new com.google.protobuf.AbstractParser<LoginRes>() {
            @java.lang.Override
            public LoginRes parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LoginRes(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<LoginRes> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LoginRes> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public CommonProto.LoginRes getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RoleOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Role)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 rid = 1;</code>
         *
         * @return The rid.
         */
        long getRid();

        /**
         * <code>string roleName = 2;</code>
         *
         * @return The roleName.
         */
        java.lang.String getRoleName();

        /**
         * <code>string roleName = 2;</code>
         *
         * @return The bytes for roleName.
         */
        com.google.protobuf.ByteString
        getRoleNameBytes();

        /**
         * <code>int32 level = 3;</code>
         *
         * @return The level.
         */
        int getLevel();

        /**
         * <code>string career = 4;</code>
         *
         * @return The career.
         */
        java.lang.String getCareer();

        /**
         * <code>string career = 4;</code>
         *
         * @return The bytes for career.
         */
        com.google.protobuf.ByteString
        getCareerBytes();
    }

    /**
     * Protobuf type {@code Role}
     */
    public static final class Role extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Role)
            RoleOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Role.newBuilder() to construct.
        private Role(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Role() {
            roleName_ = "";
            career_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Role();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Role(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            rid_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            roleName_ = s;
                            break;
                        }
                        case 24: {

                            level_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            career_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return CommonProto.internal_static_Role_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return CommonProto.internal_static_Role_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            CommonProto.Role.class, CommonProto.Role.Builder.class);
        }

        public static final int RID_FIELD_NUMBER = 1;
        private long rid_;

        /**
         * <code>int64 rid = 1;</code>
         *
         * @return The rid.
         */
        @java.lang.Override
        public long getRid() {
            return rid_;
        }

        public static final int ROLENAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object roleName_;

        /**
         * <code>string roleName = 2;</code>
         *
         * @return The roleName.
         */
        @java.lang.Override
        public java.lang.String getRoleName() {
            java.lang.Object ref = roleName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                roleName_ = s;
                return s;
            }
        }

        /**
         * <code>string roleName = 2;</code>
         *
         * @return The bytes for roleName.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getRoleNameBytes() {
            java.lang.Object ref = roleName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                roleName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LEVEL_FIELD_NUMBER = 3;
        private int level_;

        /**
         * <code>int32 level = 3;</code>
         *
         * @return The level.
         */
        @java.lang.Override
        public int getLevel() {
            return level_;
        }

        public static final int CAREER_FIELD_NUMBER = 4;
        private volatile java.lang.Object career_;

        /**
         * <code>string career = 4;</code>
         *
         * @return The career.
         */
        @java.lang.Override
        public java.lang.String getCareer() {
            java.lang.Object ref = career_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                career_ = s;
                return s;
            }
        }

        /**
         * <code>string career = 4;</code>
         *
         * @return The bytes for career.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getCareerBytes() {
            java.lang.Object ref = career_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                career_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (rid_ != 0L) {
                output.writeInt64(1, rid_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roleName_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roleName_);
            }
            if (level_ != 0) {
                output.writeInt32(3, level_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(career_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, career_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (rid_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, rid_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roleName_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roleName_);
            }
            if (level_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, level_);
            }
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(career_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, career_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof CommonProto.Role)) {
                return super.equals(obj);
            }
            CommonProto.Role other = (CommonProto.Role) obj;

            if (getRid()
                    != other.getRid()) return false;
            if (!getRoleName()
                    .equals(other.getRoleName())) return false;
            if (getLevel()
                    != other.getLevel()) return false;
            if (!getCareer()
                    .equals(other.getCareer())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getRid());
            hash = (37 * hash) + ROLENAME_FIELD_NUMBER;
            hash = (53 * hash) + getRoleName().hashCode();
            hash = (37 * hash) + LEVEL_FIELD_NUMBER;
            hash = (53 * hash) + getLevel();
            hash = (37 * hash) + CAREER_FIELD_NUMBER;
            hash = (53 * hash) + getCareer().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static CommonProto.Role parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.Role parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.Role parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.Role parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.Role parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static CommonProto.Role parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static CommonProto.Role parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.Role parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.Role parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static CommonProto.Role parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static CommonProto.Role parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static CommonProto.Role parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(CommonProto.Role prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Role}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Role)
                CommonProto.RoleOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return CommonProto.internal_static_Role_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return CommonProto.internal_static_Role_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                CommonProto.Role.class, CommonProto.Role.Builder.class);
            }

            // Construct using CommonProto.Role.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                rid_ = 0L;

                roleName_ = "";

                level_ = 0;

                career_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return CommonProto.internal_static_Role_descriptor;
            }

            @java.lang.Override
            public CommonProto.Role getDefaultInstanceForType() {
                return CommonProto.Role.getDefaultInstance();
            }

            @java.lang.Override
            public CommonProto.Role build() {
                CommonProto.Role result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public CommonProto.Role buildPartial() {
                CommonProto.Role result = new CommonProto.Role(this);
                result.rid_ = rid_;
                result.roleName_ = roleName_;
                result.level_ = level_;
                result.career_ = career_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof CommonProto.Role) {
                    return mergeFrom((CommonProto.Role) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(CommonProto.Role other) {
                if (other == CommonProto.Role.getDefaultInstance()) return this;
                if (other.getRid() != 0L) {
                    setRid(other.getRid());
                }
                if (!other.getRoleName().isEmpty()) {
                    roleName_ = other.roleName_;
                    onChanged();
                }
                if (other.getLevel() != 0) {
                    setLevel(other.getLevel());
                }
                if (!other.getCareer().isEmpty()) {
                    career_ = other.career_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                CommonProto.Role parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (CommonProto.Role) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long rid_;

            /**
             * <code>int64 rid = 1;</code>
             *
             * @return The rid.
             */
            @java.lang.Override
            public long getRid() {
                return rid_;
            }

            /**
             * <code>int64 rid = 1;</code>
             *
             * @param value The rid to set.
             * @return This builder for chaining.
             */
            public Builder setRid(long value) {

                rid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 rid = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRid() {

                rid_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object roleName_ = "";

            /**
             * <code>string roleName = 2;</code>
             *
             * @return The roleName.
             */
            public java.lang.String getRoleName() {
                java.lang.Object ref = roleName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    roleName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string roleName = 2;</code>
             *
             * @return The bytes for roleName.
             */
            public com.google.protobuf.ByteString
            getRoleNameBytes() {
                java.lang.Object ref = roleName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    roleName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string roleName = 2;</code>
             *
             * @param value The roleName to set.
             * @return This builder for chaining.
             */
            public Builder setRoleName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                roleName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string roleName = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearRoleName() {

                roleName_ = getDefaultInstance().getRoleName();
                onChanged();
                return this;
            }

            /**
             * <code>string roleName = 2;</code>
             *
             * @param value The bytes for roleName to set.
             * @return This builder for chaining.
             */
            public Builder setRoleNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                roleName_ = value;
                onChanged();
                return this;
            }

            private int level_;

            /**
             * <code>int32 level = 3;</code>
             *
             * @return The level.
             */
            @java.lang.Override
            public int getLevel() {
                return level_;
            }

            /**
             * <code>int32 level = 3;</code>
             *
             * @param value The level to set.
             * @return This builder for chaining.
             */
            public Builder setLevel(int value) {

                level_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 level = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLevel() {

                level_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object career_ = "";

            /**
             * <code>string career = 4;</code>
             *
             * @return The career.
             */
            public java.lang.String getCareer() {
                java.lang.Object ref = career_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    career_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string career = 4;</code>
             *
             * @return The bytes for career.
             */
            public com.google.protobuf.ByteString
            getCareerBytes() {
                java.lang.Object ref = career_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    career_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string career = 4;</code>
             *
             * @param value The career to set.
             * @return This builder for chaining.
             */
            public Builder setCareer(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                career_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string career = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCareer() {

                career_ = getDefaultInstance().getCareer();
                onChanged();
                return this;
            }

            /**
             * <code>string career = 4;</code>
             *
             * @param value The bytes for career to set.
             * @return This builder for chaining.
             */
            public Builder setCareerBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                career_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Role)
        }

        // @@protoc_insertion_point(class_scope:Role)
        private static final CommonProto.Role DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new CommonProto.Role();
        }

        public static CommonProto.Role getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Role>
                PARSER = new com.google.protobuf.AbstractParser<Role>() {
            @java.lang.Override
            public Role parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Role(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Role> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Role> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public CommonProto.Role getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginReq_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginReq_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_LoginRes_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_LoginRes_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Role_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Role_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021file/Common.proto\".\n\010LoginReq\022\020\n\010usern" +
                        "ame\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\",\n\010LoginRes\022" +
                        "\013\n\003uid\030\001 \001(\003\022\023\n\004role\030\002 \003(\0132\005.Role\"D\n\004Rol" +
                        "e\022\013\n\003rid\030\001 \001(\003\022\020\n\010roleName\030\002 \001(\t\022\r\n\005leve" +
                        "l\030\003 \001(\005\022\016\n\006career\030\004 \001(\tB\017B\013CommonProtoH\001" +
                        "b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_LoginReq_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_LoginReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginReq_descriptor,
                new java.lang.String[]{"Username", "Password",});
        internal_static_LoginRes_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_LoginRes_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_LoginRes_descriptor,
                new java.lang.String[]{"Uid", "Role",});
        internal_static_Role_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Role_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Role_descriptor,
                new java.lang.String[]{"Rid", "RoleName", "Level", "Career",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
