package com.cream.helper.core.net.proto.clazz;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file/Test.proto

public final class TestProto {
    private TestProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface Test1OrBuilder extends
            // @@protoc_insertion_point(interface_extends:Test1)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string msg = 1;</code>
         *
         * @return The msg.
         */
        java.lang.String getMsg();

        /**
         * <code>string msg = 1;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();

        /**
         * <code>.Test1Inner inner = 2;</code>
         *
         * @return Whether the inner field is set.
         */
        boolean hasInner();

        /**
         * <code>.Test1Inner inner = 2;</code>
         *
         * @return The inner.
         */
        TestProto.Test1Inner getInner();

        /**
         * <code>.Test1Inner inner = 2;</code>
         */
        TestProto.Test1InnerOrBuilder getInnerOrBuilder();
    }

    /**
     * Protobuf type {@code Test1}
     */
    public static final class Test1 extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Test1)
            Test1OrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Test1.newBuilder() to construct.
        private Test1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Test1() {
            msg_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Test1();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Test1(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        case 18: {
                            TestProto.Test1Inner.Builder subBuilder = null;
                            if (inner_ != null) {
                                subBuilder = inner_.toBuilder();
                            }
                            inner_ = input.readMessage(TestProto.Test1Inner.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(inner_);
                                inner_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestProto.internal_static_Test1_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestProto.internal_static_Test1_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestProto.Test1.class, TestProto.Test1.Builder.class);
        }

        public static final int MSG_FIELD_NUMBER = 1;
        private volatile java.lang.Object msg_;

        /**
         * <code>string msg = 1;</code>
         *
         * @return The msg.
         */
        @java.lang.Override
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <code>string msg = 1;</code>
         *
         * @return The bytes for msg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int INNER_FIELD_NUMBER = 2;
        private TestProto.Test1Inner inner_;

        /**
         * <code>.Test1Inner inner = 2;</code>
         *
         * @return Whether the inner field is set.
         */
        @java.lang.Override
        public boolean hasInner() {
            return inner_ != null;
        }

        /**
         * <code>.Test1Inner inner = 2;</code>
         *
         * @return The inner.
         */
        @java.lang.Override
        public TestProto.Test1Inner getInner() {
            return inner_ == null ? TestProto.Test1Inner.getDefaultInstance() : inner_;
        }

        /**
         * <code>.Test1Inner inner = 2;</code>
         */
        @java.lang.Override
        public TestProto.Test1InnerOrBuilder getInnerOrBuilder() {
            return getInner();
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
            }
            if (inner_ != null) {
                output.writeMessage(2, getInner());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
            }
            if (inner_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getInner());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestProto.Test1)) {
                return super.equals(obj);
            }
            TestProto.Test1 other = (TestProto.Test1) obj;

            if (!getMsg()
                    .equals(other.getMsg())) return false;
            if (hasInner() != other.hasInner()) return false;
            if (hasInner()) {
                if (!getInner()
                        .equals(other.getInner())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            if (hasInner()) {
                hash = (37 * hash) + INNER_FIELD_NUMBER;
                hash = (53 * hash) + getInner().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestProto.Test1 parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1 parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1 parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1 parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1 parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1 parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1 parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test1 parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test1 parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestProto.Test1 parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test1 parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test1 parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestProto.Test1 prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Test1}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Test1)
                TestProto.Test1OrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestProto.internal_static_Test1_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestProto.internal_static_Test1_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestProto.Test1.class, TestProto.Test1.Builder.class);
            }

            // Construct using TestProto.Test1.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                msg_ = "";

                if (innerBuilder_ == null) {
                    inner_ = null;
                } else {
                    inner_ = null;
                    innerBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestProto.internal_static_Test1_descriptor;
            }

            @java.lang.Override
            public TestProto.Test1 getDefaultInstanceForType() {
                return TestProto.Test1.getDefaultInstance();
            }

            @java.lang.Override
            public TestProto.Test1 build() {
                TestProto.Test1 result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TestProto.Test1 buildPartial() {
                TestProto.Test1 result = new TestProto.Test1(this);
                result.msg_ = msg_;
                if (innerBuilder_ == null) {
                    result.inner_ = inner_;
                } else {
                    result.inner_ = innerBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestProto.Test1) {
                    return mergeFrom((TestProto.Test1) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestProto.Test1 other) {
                if (other == TestProto.Test1.getDefaultInstance()) return this;
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                if (other.hasInner()) {
                    mergeInner(other.getInner());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestProto.Test1 parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestProto.Test1) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object msg_ = "";

            /**
             * <code>string msg = 1;</code>
             *
             * @return The msg.
             */
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @return The bytes for msg.
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            private TestProto.Test1Inner inner_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    TestProto.Test1Inner, TestProto.Test1Inner.Builder, TestProto.Test1InnerOrBuilder> innerBuilder_;

            /**
             * <code>.Test1Inner inner = 2;</code>
             *
             * @return Whether the inner field is set.
             */
            public boolean hasInner() {
                return innerBuilder_ != null || inner_ != null;
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             *
             * @return The inner.
             */
            public TestProto.Test1Inner getInner() {
                if (innerBuilder_ == null) {
                    return inner_ == null ? TestProto.Test1Inner.getDefaultInstance() : inner_;
                } else {
                    return innerBuilder_.getMessage();
                }
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public Builder setInner(TestProto.Test1Inner value) {
                if (innerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    inner_ = value;
                    onChanged();
                } else {
                    innerBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public Builder setInner(
                    TestProto.Test1Inner.Builder builderForValue) {
                if (innerBuilder_ == null) {
                    inner_ = builderForValue.build();
                    onChanged();
                } else {
                    innerBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public Builder mergeInner(TestProto.Test1Inner value) {
                if (innerBuilder_ == null) {
                    if (inner_ != null) {
                        inner_ =
                                TestProto.Test1Inner.newBuilder(inner_).mergeFrom(value).buildPartial();
                    } else {
                        inner_ = value;
                    }
                    onChanged();
                } else {
                    innerBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public Builder clearInner() {
                if (innerBuilder_ == null) {
                    inner_ = null;
                    onChanged();
                } else {
                    inner_ = null;
                    innerBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public TestProto.Test1Inner.Builder getInnerBuilder() {

                onChanged();
                return getInnerFieldBuilder().getBuilder();
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            public TestProto.Test1InnerOrBuilder getInnerOrBuilder() {
                if (innerBuilder_ != null) {
                    return innerBuilder_.getMessageOrBuilder();
                } else {
                    return inner_ == null ?
                            TestProto.Test1Inner.getDefaultInstance() : inner_;
                }
            }

            /**
             * <code>.Test1Inner inner = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    TestProto.Test1Inner, TestProto.Test1Inner.Builder, TestProto.Test1InnerOrBuilder>
            getInnerFieldBuilder() {
                if (innerBuilder_ == null) {
                    innerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            TestProto.Test1Inner, TestProto.Test1Inner.Builder, TestProto.Test1InnerOrBuilder>(
                            getInner(),
                            getParentForChildren(),
                            isClean());
                    inner_ = null;
                }
                return innerBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Test1)
        }

        // @@protoc_insertion_point(class_scope:Test1)
        private static final TestProto.Test1 DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestProto.Test1();
        }

        public static TestProto.Test1 getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Test1>
                PARSER = new com.google.protobuf.AbstractParser<Test1>() {
            @java.lang.Override
            public Test1 parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Test1(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Test1> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Test1> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TestProto.Test1 getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface Test1InnerOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Test1Inner)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated string str = 1;</code>
         *
         * @return A list containing the str.
         */
        java.util.List<java.lang.String>
        getStrList();

        /**
         * <code>repeated string str = 1;</code>
         *
         * @return The count of str.
         */
        int getStrCount();

        /**
         * <code>repeated string str = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The str at the given index.
         */
        java.lang.String getStr(int index);

        /**
         * <code>repeated string str = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the str at the given index.
         */
        com.google.protobuf.ByteString
        getStrBytes(int index);
    }

    /**
     * Protobuf type {@code Test1Inner}
     */
    public static final class Test1Inner extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Test1Inner)
            Test1InnerOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Test1Inner.newBuilder() to construct.
        private Test1Inner(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Test1Inner() {
            str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Test1Inner();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Test1Inner(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                str_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            str_.add(s);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    str_ = str_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestProto.internal_static_Test1Inner_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestProto.internal_static_Test1Inner_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestProto.Test1Inner.class, TestProto.Test1Inner.Builder.class);
        }

        public static final int STR_FIELD_NUMBER = 1;
        private com.google.protobuf.LazyStringList str_;

        /**
         * <code>repeated string str = 1;</code>
         *
         * @return A list containing the str.
         */
        public com.google.protobuf.ProtocolStringList
        getStrList() {
            return str_;
        }

        /**
         * <code>repeated string str = 1;</code>
         *
         * @return The count of str.
         */
        public int getStrCount() {
            return str_.size();
        }

        /**
         * <code>repeated string str = 1;</code>
         *
         * @param index The index of the element to return.
         * @return The str at the given index.
         */
        public java.lang.String getStr(int index) {
            return str_.get(index);
        }

        /**
         * <code>repeated string str = 1;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the str at the given index.
         */
        public com.google.protobuf.ByteString
        getStrBytes(int index) {
            return str_.getByteString(index);
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < str_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, str_.getRaw(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            {
                int dataSize = 0;
                for (int i = 0; i < str_.size(); i++) {
                    dataSize += computeStringSizeNoTag(str_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getStrList().size();
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestProto.Test1Inner)) {
                return super.equals(obj);
            }
            TestProto.Test1Inner other = (TestProto.Test1Inner) obj;

            if (!getStrList()
                    .equals(other.getStrList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getStrCount() > 0) {
                hash = (37 * hash) + STR_FIELD_NUMBER;
                hash = (53 * hash) + getStrList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestProto.Test1Inner parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1Inner parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1Inner parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1Inner parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1Inner parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test1Inner parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test1Inner parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test1Inner parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test1Inner parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestProto.Test1Inner parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test1Inner parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test1Inner parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestProto.Test1Inner prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Test1Inner}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Test1Inner)
                TestProto.Test1InnerOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestProto.internal_static_Test1Inner_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestProto.internal_static_Test1Inner_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestProto.Test1Inner.class, TestProto.Test1Inner.Builder.class);
            }

            // Construct using TestProto.Test1Inner.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestProto.internal_static_Test1Inner_descriptor;
            }

            @java.lang.Override
            public TestProto.Test1Inner getDefaultInstanceForType() {
                return TestProto.Test1Inner.getDefaultInstance();
            }

            @java.lang.Override
            public TestProto.Test1Inner build() {
                TestProto.Test1Inner result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TestProto.Test1Inner buildPartial() {
                TestProto.Test1Inner result = new TestProto.Test1Inner(this);
                int from_bitField0_ = bitField0_;
                if (((bitField0_ & 0x00000001) != 0)) {
                    str_ = str_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.str_ = str_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestProto.Test1Inner) {
                    return mergeFrom((TestProto.Test1Inner) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestProto.Test1Inner other) {
                if (other == TestProto.Test1Inner.getDefaultInstance()) return this;
                if (!other.str_.isEmpty()) {
                    if (str_.isEmpty()) {
                        str_ = other.str_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureStrIsMutable();
                        str_.addAll(other.str_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestProto.Test1Inner parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestProto.Test1Inner) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.LazyStringList str_ = com.google.protobuf.LazyStringArrayList.EMPTY;

            private void ensureStrIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    str_ = new com.google.protobuf.LazyStringArrayList(str_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @return A list containing the str.
             */
            public com.google.protobuf.ProtocolStringList
            getStrList() {
                return str_.getUnmodifiableView();
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @return The count of str.
             */
            public int getStrCount() {
                return str_.size();
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param index The index of the element to return.
             * @return The str at the given index.
             */
            public java.lang.String getStr(int index) {
                return str_.get(index);
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param index The index of the value to return.
             * @return The bytes of the str at the given index.
             */
            public com.google.protobuf.ByteString
            getStrBytes(int index) {
                return str_.getByteString(index);
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param index The index to set the value at.
             * @param value The str to set.
             * @return This builder for chaining.
             */
            public Builder setStr(
                    int index, java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStrIsMutable();
                str_.set(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param value The str to add.
             * @return This builder for chaining.
             */
            public Builder addStr(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureStrIsMutable();
                str_.add(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param values The str to add.
             * @return This builder for chaining.
             */
            public Builder addAllStr(
                    java.lang.Iterable<java.lang.String> values) {
                ensureStrIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, str_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearStr() {
                str_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>repeated string str = 1;</code>
             *
             * @param value The bytes of the str to add.
             * @return This builder for chaining.
             */
            public Builder addStrBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureStrIsMutable();
                str_.add(value);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Test1Inner)
        }

        // @@protoc_insertion_point(class_scope:Test1Inner)
        private static final TestProto.Test1Inner DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestProto.Test1Inner();
        }

        public static TestProto.Test1Inner getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Test1Inner>
                PARSER = new com.google.protobuf.AbstractParser<Test1Inner>() {
            @java.lang.Override
            public Test1Inner parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Test1Inner(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Test1Inner> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Test1Inner> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TestProto.Test1Inner getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface Test2OrBuilder extends
            // @@protoc_insertion_point(interface_extends:Test2)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string msg = 1;</code>
         *
         * @return The msg.
         */
        java.lang.String getMsg();

        /**
         * <code>string msg = 1;</code>
         *
         * @return The bytes for msg.
         */
        com.google.protobuf.ByteString
        getMsgBytes();
    }

    /**
     * Protobuf type {@code Test2}
     */
    public static final class Test2 extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Test2)
            Test2OrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Test2.newBuilder() to construct.
        private Test2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Test2() {
            msg_ = "";
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Test2();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Test2(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            msg_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestProto.internal_static_Test2_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestProto.internal_static_Test2_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestProto.Test2.class, TestProto.Test2.Builder.class);
        }

        public static final int MSG_FIELD_NUMBER = 1;
        private volatile java.lang.Object msg_;

        /**
         * <code>string msg = 1;</code>
         *
         * @return The msg.
         */
        @java.lang.Override
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            }
        }

        /**
         * <code>string msg = 1;</code>
         *
         * @return The bytes for msg.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msg_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msg_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestProto.Test2)) {
                return super.equals(obj);
            }
            TestProto.Test2 other = (TestProto.Test2) obj;

            if (!getMsg()
                    .equals(other.getMsg())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + MSG_FIELD_NUMBER;
            hash = (53 * hash) + getMsg().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestProto.Test2 parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test2 parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test2 parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test2 parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test2 parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test2 parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test2 parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test2 parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test2 parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestProto.Test2 parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test2 parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test2 parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestProto.Test2 prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Test2}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Test2)
                TestProto.Test2OrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestProto.internal_static_Test2_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestProto.internal_static_Test2_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestProto.Test2.class, TestProto.Test2.Builder.class);
            }

            // Construct using TestProto.Test2.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                msg_ = "";

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestProto.internal_static_Test2_descriptor;
            }

            @java.lang.Override
            public TestProto.Test2 getDefaultInstanceForType() {
                return TestProto.Test2.getDefaultInstance();
            }

            @java.lang.Override
            public TestProto.Test2 build() {
                TestProto.Test2 result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TestProto.Test2 buildPartial() {
                TestProto.Test2 result = new TestProto.Test2(this);
                result.msg_ = msg_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestProto.Test2) {
                    return mergeFrom((TestProto.Test2) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestProto.Test2 other) {
                if (other == TestProto.Test2.getDefaultInstance()) return this;
                if (!other.getMsg().isEmpty()) {
                    msg_ = other.msg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestProto.Test2 parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestProto.Test2) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object msg_ = "";

            /**
             * <code>string msg = 1;</code>
             *
             * @return The msg.
             */
            public java.lang.String getMsg() {
                java.lang.Object ref = msg_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @return The bytes for msg.
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                java.lang.Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @param value The msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsg(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMsg() {

                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>string msg = 1;</code>
             *
             * @param value The bytes for msg to set.
             * @return This builder for chaining.
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                msg_ = value;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Test2)
        }

        // @@protoc_insertion_point(class_scope:Test2)
        private static final TestProto.Test2 DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestProto.Test2();
        }

        public static TestProto.Test2 getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Test2>
                PARSER = new com.google.protobuf.AbstractParser<Test2>() {
            @java.lang.Override
            public Test2 parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Test2(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Test2> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Test2> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TestProto.Test2 getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface Test3OrBuilder extends
            // @@protoc_insertion_point(interface_extends:Test3)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 no = 1;</code>
         *
         * @return The no.
         */
        int getNo();
    }

    /**
     * Protobuf type {@code Test3}
     */
    public static final class Test3 extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Test3)
            Test3OrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Test3.newBuilder() to construct.
        private Test3(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Test3() {
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Test3();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Test3(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            no_ = input.readInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestProto.internal_static_Test3_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestProto.internal_static_Test3_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            TestProto.Test3.class, TestProto.Test3.Builder.class);
        }

        public static final int NO_FIELD_NUMBER = 1;
        private int no_;

        /**
         * <code>int32 no = 1;</code>
         *
         * @return The no.
         */
        @java.lang.Override
        public int getNo() {
            return no_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (no_ != 0) {
                output.writeInt32(1, no_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (no_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, no_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof TestProto.Test3)) {
                return super.equals(obj);
            }
            TestProto.Test3 other = (TestProto.Test3) obj;

            if (getNo()
                    != other.getNo()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + NO_FIELD_NUMBER;
            hash = (53 * hash) + getNo();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static TestProto.Test3 parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test3 parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test3 parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test3 parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test3 parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static TestProto.Test3 parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static TestProto.Test3 parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test3 parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test3 parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static TestProto.Test3 parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static TestProto.Test3 parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static TestProto.Test3 parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(TestProto.Test3 prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Test3}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Test3)
                TestProto.Test3OrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestProto.internal_static_Test3_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestProto.internal_static_Test3_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                TestProto.Test3.class, TestProto.Test3.Builder.class);
            }

            // Construct using TestProto.Test3.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                no_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestProto.internal_static_Test3_descriptor;
            }

            @java.lang.Override
            public TestProto.Test3 getDefaultInstanceForType() {
                return TestProto.Test3.getDefaultInstance();
            }

            @java.lang.Override
            public TestProto.Test3 build() {
                TestProto.Test3 result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public TestProto.Test3 buildPartial() {
                TestProto.Test3 result = new TestProto.Test3(this);
                result.no_ = no_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof TestProto.Test3) {
                    return mergeFrom((TestProto.Test3) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(TestProto.Test3 other) {
                if (other == TestProto.Test3.getDefaultInstance()) return this;
                if (other.getNo() != 0) {
                    setNo(other.getNo());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                TestProto.Test3 parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (TestProto.Test3) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int no_;

            /**
             * <code>int32 no = 1;</code>
             *
             * @return The no.
             */
            @java.lang.Override
            public int getNo() {
                return no_;
            }

            /**
             * <code>int32 no = 1;</code>
             *
             * @param value The no to set.
             * @return This builder for chaining.
             */
            public Builder setNo(int value) {

                no_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 no = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearNo() {

                no_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Test3)
        }

        // @@protoc_insertion_point(class_scope:Test3)
        private static final TestProto.Test3 DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new TestProto.Test3();
        }

        public static TestProto.Test3 getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Test3>
                PARSER = new com.google.protobuf.AbstractParser<Test3>() {
            @java.lang.Override
            public Test3 parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Test3(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Test3> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Test3> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public TestProto.Test3 getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Test1_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Test1_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Test1Inner_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Test1Inner_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Test2_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Test2_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Test3_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Test3_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\017file/Test.proto\"0\n\005Test1\022\013\n\003msg\030\001 \001(\t\022" +
                        "\032\n\005inner\030\002 \001(\0132\013.Test1Inner\"\031\n\nTest1Inne" +
                        "r\022\013\n\003str\030\001 \003(\t\"\024\n\005Test2\022\013\n\003msg\030\001 \001(\t\"\023\n\005" +
                        "Test3\022\n\n\002no\030\001 \001(\005B\rB\tTestProtoH\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Test1_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Test1_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Test1_descriptor,
                new java.lang.String[]{"Msg", "Inner",});
        internal_static_Test1Inner_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_Test1Inner_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Test1Inner_descriptor,
                new java.lang.String[]{"Str",});
        internal_static_Test2_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_Test2_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Test2_descriptor,
                new java.lang.String[]{"Msg",});
        internal_static_Test3_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_Test3_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Test3_descriptor,
                new java.lang.String[]{"No",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
